// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230926124012_Init_1")]
    partial class Init_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Entites.ClientContacts", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Id контакта");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ClientId")
                        .HasColumnType("bigint")
                        .HasComment("Id клиента");

                    b.Property<string>("ContactType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Тип контакта");

                    b.Property<string>("ContactValue")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Значение контакта");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientContacts", t =>
                        {
                            t.HasComment("Контакты клиента");
                        });
                });

            modelBuilder.Entity("Data.Entites.Clients", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Id клиента");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Наименование клиента");

                    b.HasKey("Id");

                    b.ToTable("Clients", t =>
                        {
                            t.HasComment("Клиенты");
                        });
                });

            modelBuilder.Entity("Data.Entites.Codes", b =>
                {
                    b.Property<long>("OrderNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("order_number")
                        .HasComment("Порядковый номер");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrderNumber"));

                    b.Property<int>("Code")
                        .HasColumnType("int")
                        .HasColumnName("code")
                        .HasComment("Код");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value")
                        .HasComment("Значение кода");

                    b.HasKey("OrderNumber");

                    b.ToTable("Codes", t =>
                        {
                            t.HasComment("Коды");
                        });
                });

            modelBuilder.Entity("Data.Entites.Dates", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasComment("Id клиента");

                    b.Property<DateTime>("Dt")
                        .HasColumnType("date")
                        .HasComment("Дата клиента");

                    b.HasKey("Id", "Dt");

                    b.ToTable("Dates", t =>
                        {
                            t.HasComment("Даты клиента");
                        });
                });

            modelBuilder.Entity("Data.Entites.Logs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Первичный ключ");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("dateEnd")
                        .HasComment("Дата окончания");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("dateStart")
                        .HasComment("Дата начала");

                    b.Property<string>("In")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("in")
                        .HasComment("Данные на вход");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name")
                        .HasComment("Наименование вызываемого метода");

                    b.Property<string>("Out")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("out")
                        .HasComment("Данные на выход");

                    b.Property<bool>("Success")
                        .HasColumnType("bit")
                        .HasColumnName("success")
                        .HasComment("Признак успешного выполнения");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type")
                        .HasComment("Тип вызываемого метода");

                    b.HasKey("Id");

                    b.ToTable("Logs", t =>
                        {
                            t.HasComment("Логи");
                        });
                });

            modelBuilder.Entity("Data.Entites.ClientContacts", b =>
                {
                    b.HasOne("Data.Entites.Clients", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.Navigation("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
